language: python
python:
  - "3.8"
before_install:
  - sudo apt-get -y install aria2
  - sudo apt-get -y install cabextract
addons:
  apt:
    update: true
install:
  - pip install python-rapidjson requests
script:
  - cd data
  - python -m cProfile -s tottime deploy.py

# https://github.com/ebu/ebu-tt-live-toolkit/issues/139#issuecomment-324696334
# Build all branches, *including* gh-pages:
branches:
  only:
  - gh-pages
  - /.*/
