os: windows
language: shell       # 'language: python' is an error on Travis CI Windows
before_install:
  - sc stop WSearch
  - choco install python --version 3.8.0
  - python -m pip install --upgrade pip
  - python -m pip install python-rapidjson requests
env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install: pip install --upgrade pip
script:
  - cd data
  - python deploy.py

# https://github.com/ebu/ebu-tt-live-toolkit/issues/139#issuecomment-324696334
# Build all branches, *including* gh-pages:
branches:
  only:
  - gh-pages
  - /.*/
