name: Winbindex Periodic Update

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'
    # - cron: '15 18 * * TUE'
    - cron: '15 18 * * *'

concurrency: winbindex-periodic-update

jobs:
  update:
    runs-on: windows-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: data/gh-pages
      - name: Override out_path
        run: |
          echo ./gh-pages/data > data/.out_path_override
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Windows dependencies
        run: |
          choco install -y aria2 tor
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: v2-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('.github/workflows/deploy.yml') }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'git+https://github.com/m417z/pymultitor.git' isal mitmproxy orjson requests signify
      - name: Set up Git config
        run: |
          git config --global user.email "69083578+winbindex-deploy-bot@users.noreply.github.com"
          git config --global user.name "winbindex-deploy-bot"

          # Make sure git clean doesn't fail on long paths.
          git config --global core.longpaths true
      - name: Run periodic update
        run: |
          cd data
          python -X utf8 -u deploy.py
