name: Winbindex Periodic Update

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'
    - cron: '15 18 * * TUE'

concurrency: winbindex-periodic-update

jobs:
  update:
    runs-on: windows-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: data/gh-pages
      - name: Override out_path
        run: |
          echo ./gh-pages/data > data/.out_path_override
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Windows dependencies
        run: |
          choco install -y aria2 tor
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: v2-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('.github/workflows/deploy.yml') }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'git+https://github.com/m417z/pymultitor.git' isal mitmproxy orjson requests signify
      - name: Run periodic update
        run: |
          cd data
          python -u deploy.py
